networks:
  proxy:
    external: true
  outbound:
    external: true


services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    networks:
      - proxy
      - outbound
    restart: on-failure
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=HostRegexp(`^jellyfin\.(${INTERNAL_DOMAIN}|${PUBLIC_DOMAIN})$`)
      - traefik.http.routers.jellyfin.entryPoints=websecure
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    volumes:
      - ~/data/jellyfin:/config
      - /mnt/intenso/movies:/movies
      - /mnt/intenso/shows:/tv
      - /mnt/adata/:/media