name: keycloak

networks:
  proxy:
    external: true

services:  
  db:
    container_name: keycloak-db
    image: postgres:17
    restart: unless-stopped
    networks:
      - proxy
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data


  keycloak:
    container_name: keycloak_server
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    restart: unless-stopped
    networks:
      - proxy
    depends_on:
      - db
    ports:
      - "8080:8080"
      #- "8443:8443"
    command:
      - start
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_DB_URL_DATABASE: ${DB_DATABASE_NAME}
      KC_DB_URL_HOST: keycloak-db
      KC_HOSTNAME: https://keycloak.${INTERNAL_DOMAIN}
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      # X-Forward Headers are automatically sent by traefik (https://doc.traefik.io/traefik/getting-started/faq/#what-are-the-forwarded-headers-when-proxying-http-requests)
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.rule=HostRegexp(`^keycloak\.(${INTERNAL_DOMAIN}|${PUBLIC_DOMAIN})$`)
      - traefik.http.routers.keycloak.entryPoints=websecure
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
